### ISSUE TITLE
Restart is required?

### ISSUE THREAD

**Issue by joshdejuan** [TerryHuangHD/Windows-10-Version-Switcher#1]
Hi. After you execute this script do you need to restart de system or something?

**Comment by joshdejuan** [comment]
I answer my own question: Yes, it's required.

**Comment by TerryHuangHD** [comment]
Switch from home version to others will require 1+ times restart.
Windows will popup a dialog to hint.

Switch between pro / pro VL / enterprise VL / education VL will just finish in time.
